name: ecommerceapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # Utilities
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.13
  smooth_page_indicator: ^1.1.0

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/videos/
    - assets/logos/t-store-splash-logo-white.png
    - assets/logos/t-store-splash-logo-black.png
    - assets/images/onboarding_images.dart/sammy-line-sailor-on-mast-looking-through-telescope.gif
    - assets/images/onboarding_images.dart/sammy-line-man-and-dog-delivering-packages-on-a-moped.gif
    - assets/images/onboarding_images.dart/sammy-line-woman-in-shopping-cart-placing-order-on-smartphone.gif


fonts:
  - family: Poppins
    fonts:
      - assets/fonts/Poppins/Poppins-Regular.ttf:
          weight: 400
