name: ecommerceapp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #icons 

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #utilities


  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.13

  #statemanagement 

  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

assets:
    -assets/logos/
    -assets/videos/
    -assets/icons/
    -assets/images/
fonts:
    - family: Poppins
      fonts:
       - assets:'assets/fonts/Poppins/Poppins-Regular.ttf'
         weight:400
